accounts:
  - name: alice
    coins: ["10000000000token", "100000000000000stake"]
  - name: bob
    coins: ["5000000000token"]
validator:
  name: alice
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
faucet:
  host: ":4501"
  name: bob
  coins:
    - "5token"
host:
  rpc: ":26659"
  p2p: ":26658"
  prof: ":6061"
  grpc: ":9091"
  api: ":1318"
  frontend: ":8081"
  dev-ui: ":12346"
genesis:
  chain_id: "chainb"
init:
  home: "/mnt/d/cosmos/chainb/.chainb"